### ISSUE TITLE
Priviliges Not Sufficient Error for studentcoursemembership

### ISSUE THREAD

**Issue by amason** [jiscdev/lrw-udd-api#17]
SSP now has access to studentcoursemembership. However, I'm getting this error: "Priviliges not sufficient for this operation" when connecting to /assessmentinstance and /studentassessmentinstance endpoints.

**Comment by michaelwebbjisc** [comment]
As a workaround I have moved the SSP client scope to 'All' for now.

**Comment by ht2** [comment]
Hey @michaelwebbjisc, looking at the revision history on https://docs.google.com/spreadsheets/d/1PaZ2V5_hbS-Gs59x_xU735opyYTTFg1OG7lqMaELLG4 I can see those scopes changed as of 30th April. 

Probably need to think about how best to communicate those changes out to us as I wasn't aware of those changes been made. @andrewhickey will be handling this issue today though

**Comment by michaelwebbjisc** [comment]
Ah, OK, thanks.  I think we log everything here from now on it should solve that problem.  Does that work for everyone?

**Comment by amason** [comment]
Thanks @andrewhickey when you update it on your end, let us know here in this ticket.. Thanks!

**Comment by andrewhickey** [comment]
Updates have been applied, don't forget to check you're using the 1.2.3 endpoint otherwise you still won't have access (like I just did when testing)

**Comment by amason** [comment]
I am having SSP look into this. Will close if they encounter no issues.

**Comment by amason** [comment]
SSP now has access to / studentcoursemembership. Closing this one as complete.
